### ISSUE TITLE
test fails on v3.0.0

### ISSUE THREAD

**Issue by dvisztempacct** [bermi/disk-memoizer#4]
I ran `npm i` and when tests were automatically run, it broke:

```
$ npm i
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> disk-memoizer@3.0.0 prepublish /home/hdon/src/disk-memoizer
> npm run build


> disk-memoizer@3.0.0 build /home/hdon/src/disk-memoizer
> babel lib/ -d dist/

lib/config.js -> dist/config.js
lib/disk_memoizer.js -> dist/disk_memoizer.js
lib/gc.js -> dist/gc.js

> disk-memoizer@3.0.0 postbuild /home/hdon/src/disk-memoizer
> npm run test


> disk-memoizer@3.0.0 pretest /home/hdon/src/disk-memoizer
> npm run lint


> disk-memoizer@3.0.0 lint /home/hdon/src/disk-memoizer
> eslint lib test


> disk-memoizer@3.0.0 test /home/hdon/src/disk-memoizer
> mocha && ./test/integration/concurrent_read

notification support prerequisites not installed... cannot enable!


  Disk memoizer
    unit tests
      ✓ should know if the cache has expired
      ✓ should generate cache paths
      ✓ should allow custom cache base
      ✓ should grab and cache
      ✓ should allow using a custom marshaller
      ✓ should grab and cache
      ✓ should use a cached file and not fetch the url
      ✓ should allow 1000 concurrent requests (315ms)
      ✓ should prevent race conditions with concurrent failing requests (99ms)
      invalid JSON caused by race conditions
        ✓ should not use a cache file with incomplete JSON
    functional tests
      ✓ should cache JSON (126ms)
      ✓ should serve JSON from memory (56ms)
      ✓ should serve JSON from memory when using a custom identity
      ✓ should limit items in memory

  When performing gc
    ✓ should list files to delete
    ✓ should delete old files (102ms)


  16 passing (763ms)

Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Downloading https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg with 8 concurrent requests
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Starting download for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Running /home/hdon/src/disk-memoizer/test/integration/concurrent_read on 8 workers
Trying to access https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
Starting download for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +5s
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +5s
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +5s
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +5s
Starting download for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
  disk-memoizer [warning] Failed reading file https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from cache /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +10s
Starting download for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg
Download for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg completed
  disk-memoizer [info] Saved cache for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg on /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +0ms
  disk-memoizer [info] Using disk cache for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +6s
  disk-memoizer [info] Using disk cache for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +6s
  disk-memoizer [info] Using disk cache for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +11s
  disk-memoizer [info] Using disk cache for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg from /tmp/disk-memoizer/9b/2a/6d/641d9b7d3576652963cce823a4.cache +6s
Download for https://upload.wikimedia.org/wikipedia/commons/0/05/01E_May_15_2013_1750Z.jpg completed
/home/hdon/src/disk-memoizer/test/integration/concurrent_read:64
      throw new Error(`Only 1 download was expected. Got ${downloadCount}`);
      ^

Error: Only 1 download was expected. Got 2
    at Timeout.setInterval [as _onTimeout] (/home/hdon/src/disk-memoizer/test/integration/concurrent_read:64:13)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! disk-memoizer@3.0.0 test: `mocha && ./test/integration/concurrent_read`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the disk-memoizer@3.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hdon/.npm/_logs/2019-05-03T20_32_25_557Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! disk-memoizer@3.0.0 postbuild: `npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the disk-memoizer@3.0.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hdon/.npm/_logs/2019-05-03T20_32_25_573Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! disk-memoizer@3.0.0 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the disk-memoizer@3.0.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hdon/.npm/_logs/2019-05-03T20_32_25_592Z-debug.log
```

**Comment by bermi** [comment]
@dvisztempacct I could not reproduce this issue. I've removed babel and some pre scripts on the latest version

Would you mind reopening this ticket with further details on how to reproduce if you still  have issues with  v4.0.1?

**Comment by dvisztempacct** [comment]
I am unable to reproduce this with 4.0.1 so leaving this closed is just fine :)

Thanks!
